namespace Flexis.Application.JobApplication;

public sealed record JobFinancialDefaultsDto(decimal ApplyRate, decimal BonusRate);

public sealed record JobFinancialRatesRequest(decimal ApplyRate, decimal BonusRate);

public sealed record JobFinancialRowDto(
    Guid EntryId,
    Guid ProfileId,
    string ProfileTitle,
    string ProfileUrl,
    string SourceLabel,
    int Total,
    int Ready,
    int NotReady,
    int Applied,
    int Interviews,
    int Unapplied,
    decimal ApplyRate,
    decimal BonusRate,
    decimal Price,
    int TodayTotal,
    int TodayReady,
    int TodayNotReady,
    int TodayApplied,
    int TodayInterviews,
    int TodayUnapplied,
    decimal TodayPrice,
    int ArchivedTotal,
    int ArchivedReady,
    int ArchivedNotReady,
    int ArchivedApplied,
    int ArchivedInterviews,
    int ArchivedUnapplied,
    decimal ArchivedPrice,
    int LifetimeTotal,
    int LifetimeReady,
    int LifetimeNotReady,
    int LifetimeApplied,
    int LifetimeInterviews,
    int LifetimeUnapplied,
    decimal LifetimePrice);

public sealed record JobFinancialBoardDto(
    JobFinancialDefaultsDto Defaults,
    IReadOnlyList<JobFinancialRowDto> Rows,
    decimal AllPrice,
    int AllTotal,
    int AllReady,
    int AllNotReady,
    int AllApplied,
    int AllInterviews,
    int AllUnapplied,
    decimal TodayAllPrice,
    int TodayAllTotal,
    int TodayAllReady,
    int TodayAllNotReady,
    int TodayAllApplied,
    int TodayAllInterviews,
    int TodayAllUnapplied,
    decimal ArchivedAllPrice,
    int ArchivedAllTotal,
    int ArchivedAllReady,
    int ArchivedAllNotReady,
    int ArchivedAllApplied,
    int ArchivedAllInterviews,
    int ArchivedAllUnapplied,
    decimal LifetimeAllPrice,
    int LifetimeAllTotal,
    int LifetimeAllReady,
    int LifetimeAllNotReady,
    int LifetimeAllApplied,
    int LifetimeAllInterviews,
    int LifetimeAllUnapplied,
    IReadOnlyList<JobFinancialSnapshotDto> History);

public sealed record JobFinancialSnapshotDto(
    DateOnly CapturedOn,
    DateTimeOffset CapturedHour,
    DateTimeOffset CapturedAt,
    decimal TodayPrice,
    int TodayTotal,
    int TodayApplied,
    int TodayInterviews,
    decimal MainPrice,
    int MainTotal,
    int MainApplied,
    int MainInterviews,
    decimal ArchivedPrice,
    int ArchivedTotal,
    int ArchivedApplied,
    int ArchivedInterviews,
    decimal LifetimePrice,
    int LifetimeTotal,
    int LifetimeApplied,
    int LifetimeInterviews);

public sealed record JobStatisticsProfileDto(
    Guid ProfileId,
    string ProfileTitle,
    string ProfileUrl,
    int Applied,
    int Interviews,
    int Unapplied,
    int Ready,
    int NotReady,
    int Total,
    decimal Price,
    int TodayApplied,
    int TodayInterviews,
    int TodayUnapplied,
    int TodayReady,
    int TodayNotReady,
    int TodayTotal,
    decimal TodayPrice,
    decimal ApplyRate,
    decimal BonusRate);

public sealed record JobStatisticsPointDto(
    Guid ProfileId,
    string ProfileTitle,
    DateOnly CapturedOn,
    DateTimeOffset CapturedHour,
    int Applied,
    int Interviews,
    int Unapplied,
    int Total,
    decimal Price);

public sealed record JobStatisticsBoardDto(
    IReadOnlyList<JobStatisticsProfileDto> Profiles,
    IReadOnlyList<JobStatisticsPointDto> History,
    int AllApplied,
    int AllInterviews,
    int AllUnapplied,
    int AllReady,
    int AllNotReady,
    int AllTotal,
    decimal AllPrice,
    int TodayAllApplied,
    int TodayAllInterviews,
    int TodayAllUnapplied,
    int TodayAllReady,
    int TodayAllNotReady,
    int TodayAllTotal,
    decimal TodayAllPrice);
